[package]
name = "pwr-scoring"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"
zxcvbn = {version="2.2.1", features=["ser", "builder"]}
serde = { version = "1.0.145", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
