[package]
name = "pwr-scoring"
version = "0.1.3"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.86"
zxcvbn = {version="2.2.2", features=["ser", "builder"]}
serde = { version = "1.0.163", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
